version: '3.7'
services:

  localstack:
    image: localstack/localstack:0.10.6
    ports:
      - "4567-4597:4567-4597"
      - "9080:9080"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=9080
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./bin/docker-entrypoint-initaws.d:/docker-entrypoint-initaws.d"

